name: dashboard_kit
description: Dashboard kit
version: 0.0.1
author: 
  - Gleison M. Vasconcelos <gmvbr@gleisonmv.tech>
homepage: https://github.com/gmvbr/dashboard_kit

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: